[[main]]
  name = "GitHub"
  url = "https://github.com/henkisdabro/"
  weight = 20

[[sociallinkedin]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/henriksoderlund/"
  weight = 10
  icon = "linkedin"

[[socialtwitter]]
  name = "Twitter"
  url = "https://twitter.com/henkis/"
  weight = 30

[[socialmastodon]]
  name = "Mastodon"
  url = "https://masto.measure.chat/@henrik"
  weight = 40